# Setup
title:               Starjara
tagline:             'Blog for Starjara'
description:         ''
url:                 starjara.github.io
baseurl:             'starjara.github.io'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Star jara
  email:             park950920@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
