# Setup
title:               Starjara
tagline:             'Blog for Starjara'
description:         ''
url:                 https://starjara.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Starjara
  url:               https://starjara.github.io
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
goole_analystic_id:  UA-173570211-1


github:
  repo:              https://github.com/starjara/starjara.github.io  
